name: Run Kotlin console app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Run Kotlin script
      run: |
        sudo apt-get update
        sudo apt-get install -y kotlin
        kotlinc MopencilDocslibrary.kt -include-runtime -d MopencilDocslibrary.jar
        java -jar MopencilDocslibrary.jar
